### PR TITLE
About page edits

### PR DESCRIPTION
**Pull request by mekaufman**

### CODE REVIEW

**Review by cdmauney — CHANGES_REQUESTED** [review]
For more information, see the [IBM Cloud Schematics documentation](https://cloud.ibm.com/docs/schematics).

**Review by cdmauney — CHANGES_REQUESTED** [review]
"The LEMP template is an IBM Cloud Schematics template that is used to create a virtual machine instance and configure it with the "LEMP" stack: Linux, NGINX, MySQL (mariadb), and PHP."

Use "virtual server instance" instead of "virtual machine instance" to be consistent with the rest of the console.

**Review by cdmauney — CHANGES_REQUESTED** [review]
"The use of `terraform destroy` results in deletion of all resources including the IBM Cloud database service instance. Billing for virtual server instances (VSIs) and IBM Cloud database terminates on the hour."

Edits:
Running the `terraform destroy` command deletes all resources, including the IBM Cloud database service instance. 

And the second sentence isn't clear to me. Billing ends on the hour after I run the destroy command?

**Review by cdmauney — CHANGES_REQUESTED** [review]
Set the following variables before you use the template:

* `softlayer_username` is your infrastructure user name. Go to **Access (IAM)** > **Users**, and select your name. Then, verify the user name is listed in the VPN password section.
* `softlayer_api_key` is a classic infrastructure API key. Go to **Access (IAM)** > **Users**, and select your name. Then, verify that a classic infrastructure API key is included in the API keys section. If you don't have one already, you can create one from the [IBM Cloud API keys page](https://cloud.ibm.com/iam/apikeys).

**Review by cdmauney — CHANGES_REQUESTED** [review]
The data center to create resources in, for example, dal13. 

The domain for the instance, for example, domain.dev.

The hostname for the instance, for example, vm1. 

Enter your classic infrastructure API key. See the [IBM Cloud API keys page](https://cloud.ibm.com/iam/apikeys) to get the details of an existing API key or to create a new one. 

Enter your classic infrastructure user name. Go to **Access (IAM)** > **Users**, and select your name. Then, locate your user name in the VPN password section. 

Your public key file is saved to a `id_rsa.pub` file in the `.ssh` subdirectory of your home directory. 

The default user name for the virtual machine, for example, the root user for UNIX operating systems. -- Should "virtual machine" be "virtual server instance"?

**Comment by cdmauney** [comment]
@mekaufman See review comments above.

**Comment by mekaufman** [comment]
Ready to merge.

**Review by cdmauney — CHANGES_REQUESTED** [review]
For more information about how to use the template, see the [IBM Cloud Schematics documentation](https://cloud.ibm.com/docs/schematics).

Set the following variables before you use the template:

If you don't have one already, you can create one from the [IBM Cloud API keys page](https://cloud.ibm.com/iam/apikeys).

**Comment by cdmauney** [comment]
@mekaufman Just a few minor fixes.

**Pull request merged**
